FROM twalter/openshift-nginx:stable-alpine

LABEL io.k8s.description="FCC nginx-static" \
    io.k8s.display-name="FCC nginx-static image" \
    io.openshift.expose-services="8088:http" \
    io.openshift.tags="nginx" \
    io.openshift.s2i.scripts-url=image:///usr/libexec/s2i

USER root
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY docker/nginx/root/ /
COPY docker/nginx/s2i/bin/ /usr/libexec/s2i

RUN chmod -R g+rwx /etc/nginx
USER nginx

EXPOSE 8088

ENV NGINX_PORT=8088 \
    SSL_CONFIG="" \
    NGINX_CONF=/etc/nginx/conf.d/static-no-cache.conf.template

CMD ["/usr/libexec/s2i/run"]

COPY --chown=nginx:0 allure-report /usr/share/nginx/html