FROM python:3.8.5-alpine3.12
USER root
# update apk repo
RUN echo "https://dl-4.alpinelinux.org/alpine/v3.10/main" >> /etc/apk/repositories && \
    echo "https://dl-4.alpinelinux.org/alpine/v3.10/community" >> /etc/apk/repositories

# install chromedriver
RUN apk update
RUN apk add --no-cache chromium chromium-chromedriver tzdata 

# Get all the prereqs
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-bin-2.30-r0.apk
RUN apk add glibc-2.30-r0.apk
RUN apk add glibc-bin-2.30-r0.apk

# And of course we need Firefox if we actually want to *use* GeckoDriver
RUN apk add firefox

# Browsers version
# Firefox -esr=60.9.0-r0
# Chrome

# Then install GeckoDriver
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
RUN tar -zxf geckodriver-v0.27.0-linux64.tar.gz -C /usr/bin
RUN geckodriver --version

# upgrade pip
RUN pip install --upgrade pip

# install selenium
RUN pip install selenium==3.141.0 dateutils requests pytest
WORKDIR /usr/workspace
COPY * /usr/workspace/
RUN pip install -r requirements.txt
# RUN pip install allure-pytest allure-python-commons webdriver-manager selenium==3.141.0 requests pytest
RUN ls

ENV TZ Europe/Moscow

